### ISSUE TITLE
Code Review - damiwee

### ISSUE THREAD

**Issue by StanleyW00** [AY2324S2-CS2113-T11-1/tp#121]
Overall good job in maintaining code quality and good usage of exceptions and assertions!

There is an unnecessary new line under `throw new ReflectException("Key in valid favourite reflection ID, between 1 and 5");`

![image](https://github.com/AY2324S2-CS2113-T11-1/tp/assets/110610562/2b27907f-aac4-4757-b020-656f0aa054c9)

**Comment by damiwee** [comment]
Noted with thanks
