### ISSUE TITLE
Code Review - Daviancold

### ISSUE THREAD

**Issue by StanleyW00** [AY2324S2-CS2113-T11-1/tp#122]
Overall good job in maintaining code quality and good usage of exceptions and assertions!

Perhaps, you could make the add goals method so that it reduces the arrowhead style.
![image](https://github.com/AY2324S2-CS2113-T11-1/tp/assets/110610562/d19560eb-897c-48bd-a5ab-c26f6eaa8380)

**Comment by Daviancold** [comment]
Will do, thank you for pointing it out!
