### ISSUE TITLE
Code Review - JingHaoooo

### ISSUE THREAD

**Issue by StanleyW00** [AY2324S2-CS2113-T11-1/tp#123]
Overall good job in maintaining code quality and good usage of exceptions and assertions!

Perhaps, you could abstract the override run method in TimerTask class to be in another file to improve readability.
![image](https://github.com/AY2324S2-CS2113-T11-1/tp/assets/110610562/cb7924a9-2b40-43a9-941a-84c8d64fde31)

**Comment by JingHaoooo** [comment]
I get where you are coming from. While making it into an abstract class will surely improve readability, it will inevitably increase the complexity of the codes.
