### ISSUE TITLE
Code Review - OKW32

### ISSUE THREAD

**Issue by StanleyW00** [AY2324S2-CS2113-T11-1/tp#124]
Overall good job in maintaining code quality and good usage of exceptions and assertions!

Perhaps, you could combine these loops into a single loop as the conditions are the same.
![image](https://github.com/AY2324S2-CS2113-T11-1/tp/assets/110610562/2d6bc9e7-d1b9-4bd5-9280-4c240fe0cf75)

Perhaps, you could abstract some parts of this method to reduce arrowhead style
![image](https://github.com/AY2324S2-CS2113-T11-1/tp/assets/110610562/984016fd-6e91-41a9-aa7f-a93cde9c4498)

**Comment by OKW32** [comment]
For the single loop, while the condition is the same, creating it to a single loop might introduce arrow head style code.  Will change the part of the code to prevent arrowhead style.
