### ISSUE TITLE
[PE-D][Tester D] Lack of 'help' for sleep command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T11-1/tp#154]
Do include a help table for sleep, as you did for fitness so that users can take a look at how to send commands!

![Screenshot 2024-04-05 at 4.52.01 PM.png](https://raw.githubusercontent.com/dextboy/ped/main/files/5331603f-ced1-4d45-a707-bedae9bedccc.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: dextboy/ped#1

**Comment by OKW32** [comment]
Thanks for the suggestion, will add it in!
