### ISSUE TITLE
[PE-D][Tester D] Lack of save feature for sleep

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T11-1/tp#177]
Currently, the date and time for the sleep feature is not saved when exiting and re-entering the programme. Do consider improving the save feature for sleep to account for this!
![Screenshot 2024-04-05 at 5.36.53 PM.png](https://raw.githubusercontent.com/dextboy/ped/main/files/9c93dafa-38b4-4190-af0e-842d2951fbf0.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: dextboy/ped#8

**Comment by OKW32** [comment]
Auto save/delete comes with its pros and cons, in future versions, we will implement what's preferred. Thanks for the suggestion!
